services:
  db:
    image: postgres:15-alpine
    container_name: lootsafe-db
    restart: always
    environment:
      POSTGRES_DB: lootsafedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: lootsafe-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/lootsafedb
      - DB_DRIVER=org.postgresql.Driver
      - DB_USER=postgres
      - DB_PASS=rootpassword
      - DB_DIALECT=org.hibernate.dialect.PostgreSQLDialect

      - LOOTSAFE_CRYPTO_KEY=${LOOTSAFE_CRYPTO_KEY}
      - LOOTSAFE_CRYPTO_KEY_APP=${LOOTSAFE_CRYPTO_KEY_APP}
      - LOOTSAFE_ADMIN_API_KEY=${LOOTSAFE_ADMIN_API_KEY}
      - LOOTSAFE_MP_TOKEN=${LOOTSAFE_MP_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - CORS_ORIGIN=${CORS_ORIGIN}

volumes:
  postgres_data: