# --- Banco H2 em memória ---
#spring.datasource.url=jdbc:postgresql://localhost:5432/lootsafedb_dev
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- H2 Console ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Flyway ---
spring.flyway.enabled=false

# --- JWT ---
lootsafe.jwt.secret=dev-secret-key-for-local-testing-only-not-for-production
lootsafe.jwt.expiration=60

# --- Chaves de segurança (base64 AES-128) ---
lootsafe.security.encryption-key=zdVq4xVoYVpP7ykmCgvowg==
lootsafe.security.admin-api-key=dev-admin-key-1234
lootsafe.access-token=dev-mp-token
lootsafe.secret-key=dev-webhook-secret

# --- Mail ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dev@lootsafe.com
spring.mail.password=dev123

# --- Logs verbosos ---
logging.level.root=INFO
logging.level.com.lootsafe=DEBUG
logging.level.com.lootsafe.security.ApiKeyFilter=DEBUG
logging.level.com.lootsafe.config.SecurityConfig=DEBUG
logging.level.org.springframework.security=DEBUG

# --- ADMIN ----
email_admin=admin@lootsafe.com
admin_name=ADMIN
admin_password=admin123
